# Generated by Django 4.0.3 on 2023-01-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='DistrictType',
            new_name='District',
        ),
        migrations.AlterField(
            model_name='baptism',
            name='BaptismNo',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='communicant',
            name='CommunicantNo',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='Address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='Contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='NextofkinContact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='baptism',
            table='baptism',
        ),
        migrations.AlterModelTable(
            name='communicant',
            table='communicant',
        ),
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
