# Generated by Django 4.0.3 on 2023-01-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_alter_baptism_baptismno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Age',
            field=models.CharField(max_length=200),
        ),
    ]
